name: Math Issue Template
description: Use this template to report any issue
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Bug
        - Build/Install
        - Performance
        - Support
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
        - Others
    validations:
      required: true
  - type: dropdown
    id: Code
    attributes:
      label: Custom Code
      description: 
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: Math
    attributes:
      label: Math Version
      description:
      placeholder: e.g., 0.0.1
    validations:
      required: true
  - type: input
    id: Node
    attributes:
      label: NodeJS Version
      description: 
      placeholder: e.g., 16.14
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Current Behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
      render: shell
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Standalone code to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum necessary to generate the problem.
      placeholder: Tell us what you see!
      value: 
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
