module.exports = {
    docs: [
        {
            type: 'doc',
            id: 'guide/getting-started',
            label: 'Guide',
        },
        {
            type: 'doc',
            id: 'reference/home',
            label: 'Reference',
        },
    ],
    guide: [
        {
            type: 'doc',
            id: 'intro',
            label: 'Docs',
        },
        {
            type: 'autogenerated',
            dirName: 'guide',
        },
    ],
    reference: [
        {
            type: 'doc',
            id: 'intro',
            label: 'Docs',
        },
        {
            type: 'autogenerated',
            dirName: 'reference',
        },
    ],
};
